// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package pong;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PongDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pong.PongData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    boolean hasBat();
    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    pong.Api.Bat getBat();
    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    pong.Api.BatOrBuilder getBatOrBuilder();

    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    boolean hasBall();
    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    pong.Api.Ball getBall();
    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    pong.Api.BallOrBuilder getBallOrBuilder();

    /**
     * <code>optional bool hit = 3;</code>
     */
    boolean getHit();
  }
  /**
   * Protobuf type {@code pong.PongData}
   */
  public  static final class PongData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pong.PongData)
      PongDataOrBuilder {
    // Use PongData.newBuilder() to construct.
    private PongData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PongData() {
      hit_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PongData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              pong.Api.Bat.Builder subBuilder = null;
              if (bat_ != null) {
                subBuilder = bat_.toBuilder();
              }
              bat_ = input.readMessage(pong.Api.Bat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bat_);
                bat_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              pong.Api.Ball.Builder subBuilder = null;
              if (ball_ != null) {
                subBuilder = ball_.toBuilder();
              }
              ball_ = input.readMessage(pong.Api.Ball.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ball_);
                ball_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              hit_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pong.Api.internal_static_pong_PongData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pong.Api.internal_static_pong_PongData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pong.Api.PongData.class, pong.Api.PongData.Builder.class);
    }

    public static final int BAT_FIELD_NUMBER = 1;
    private pong.Api.Bat bat_;
    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    public boolean hasBat() {
      return bat_ != null;
    }
    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    public pong.Api.Bat getBat() {
      return bat_ == null ? pong.Api.Bat.getDefaultInstance() : bat_;
    }
    /**
     * <code>optional .pong.Bat bat = 1;</code>
     */
    public pong.Api.BatOrBuilder getBatOrBuilder() {
      return getBat();
    }

    public static final int BALL_FIELD_NUMBER = 2;
    private pong.Api.Ball ball_;
    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    public boolean hasBall() {
      return ball_ != null;
    }
    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    public pong.Api.Ball getBall() {
      return ball_ == null ? pong.Api.Ball.getDefaultInstance() : ball_;
    }
    /**
     * <code>optional .pong.Ball ball = 2;</code>
     */
    public pong.Api.BallOrBuilder getBallOrBuilder() {
      return getBall();
    }

    public static final int HIT_FIELD_NUMBER = 3;
    private boolean hit_;
    /**
     * <code>optional bool hit = 3;</code>
     */
    public boolean getHit() {
      return hit_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bat_ != null) {
        output.writeMessage(1, getBat());
      }
      if (ball_ != null) {
        output.writeMessage(2, getBall());
      }
      if (hit_ != false) {
        output.writeBool(3, hit_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bat_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBat());
      }
      if (ball_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBall());
      }
      if (hit_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, hit_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pong.Api.PongData)) {
        return super.equals(obj);
      }
      pong.Api.PongData other = (pong.Api.PongData) obj;

      boolean result = true;
      result = result && (hasBat() == other.hasBat());
      if (hasBat()) {
        result = result && getBat()
            .equals(other.getBat());
      }
      result = result && (hasBall() == other.hasBall());
      if (hasBall()) {
        result = result && getBall()
            .equals(other.getBall());
      }
      result = result && (getHit()
          == other.getHit());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBat()) {
        hash = (37 * hash) + BAT_FIELD_NUMBER;
        hash = (53 * hash) + getBat().hashCode();
      }
      if (hasBall()) {
        hash = (37 * hash) + BALL_FIELD_NUMBER;
        hash = (53 * hash) + getBall().hashCode();
      }
      hash = (37 * hash) + HIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHit());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pong.Api.PongData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.PongData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.PongData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.PongData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.PongData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.PongData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.PongData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pong.Api.PongData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.PongData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.PongData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pong.Api.PongData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pong.PongData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pong.PongData)
        pong.Api.PongDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pong.Api.internal_static_pong_PongData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pong.Api.internal_static_pong_PongData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pong.Api.PongData.class, pong.Api.PongData.Builder.class);
      }

      // Construct using pong.Api.PongData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (batBuilder_ == null) {
          bat_ = null;
        } else {
          bat_ = null;
          batBuilder_ = null;
        }
        if (ballBuilder_ == null) {
          ball_ = null;
        } else {
          ball_ = null;
          ballBuilder_ = null;
        }
        hit_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pong.Api.internal_static_pong_PongData_descriptor;
      }

      public pong.Api.PongData getDefaultInstanceForType() {
        return pong.Api.PongData.getDefaultInstance();
      }

      public pong.Api.PongData build() {
        pong.Api.PongData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pong.Api.PongData buildPartial() {
        pong.Api.PongData result = new pong.Api.PongData(this);
        if (batBuilder_ == null) {
          result.bat_ = bat_;
        } else {
          result.bat_ = batBuilder_.build();
        }
        if (ballBuilder_ == null) {
          result.ball_ = ball_;
        } else {
          result.ball_ = ballBuilder_.build();
        }
        result.hit_ = hit_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pong.Api.PongData) {
          return mergeFrom((pong.Api.PongData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pong.Api.PongData other) {
        if (other == pong.Api.PongData.getDefaultInstance()) return this;
        if (other.hasBat()) {
          mergeBat(other.getBat());
        }
        if (other.hasBall()) {
          mergeBall(other.getBall());
        }
        if (other.getHit() != false) {
          setHit(other.getHit());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pong.Api.PongData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pong.Api.PongData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private pong.Api.Bat bat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pong.Api.Bat, pong.Api.Bat.Builder, pong.Api.BatOrBuilder> batBuilder_;
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public boolean hasBat() {
        return batBuilder_ != null || bat_ != null;
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public pong.Api.Bat getBat() {
        if (batBuilder_ == null) {
          return bat_ == null ? pong.Api.Bat.getDefaultInstance() : bat_;
        } else {
          return batBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public Builder setBat(pong.Api.Bat value) {
        if (batBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bat_ = value;
          onChanged();
        } else {
          batBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public Builder setBat(
          pong.Api.Bat.Builder builderForValue) {
        if (batBuilder_ == null) {
          bat_ = builderForValue.build();
          onChanged();
        } else {
          batBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public Builder mergeBat(pong.Api.Bat value) {
        if (batBuilder_ == null) {
          if (bat_ != null) {
            bat_ =
              pong.Api.Bat.newBuilder(bat_).mergeFrom(value).buildPartial();
          } else {
            bat_ = value;
          }
          onChanged();
        } else {
          batBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public Builder clearBat() {
        if (batBuilder_ == null) {
          bat_ = null;
          onChanged();
        } else {
          bat_ = null;
          batBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public pong.Api.Bat.Builder getBatBuilder() {
        
        onChanged();
        return getBatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      public pong.Api.BatOrBuilder getBatOrBuilder() {
        if (batBuilder_ != null) {
          return batBuilder_.getMessageOrBuilder();
        } else {
          return bat_ == null ?
              pong.Api.Bat.getDefaultInstance() : bat_;
        }
      }
      /**
       * <code>optional .pong.Bat bat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pong.Api.Bat, pong.Api.Bat.Builder, pong.Api.BatOrBuilder> 
          getBatFieldBuilder() {
        if (batBuilder_ == null) {
          batBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pong.Api.Bat, pong.Api.Bat.Builder, pong.Api.BatOrBuilder>(
                  getBat(),
                  getParentForChildren(),
                  isClean());
          bat_ = null;
        }
        return batBuilder_;
      }

      private pong.Api.Ball ball_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pong.Api.Ball, pong.Api.Ball.Builder, pong.Api.BallOrBuilder> ballBuilder_;
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public boolean hasBall() {
        return ballBuilder_ != null || ball_ != null;
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public pong.Api.Ball getBall() {
        if (ballBuilder_ == null) {
          return ball_ == null ? pong.Api.Ball.getDefaultInstance() : ball_;
        } else {
          return ballBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public Builder setBall(pong.Api.Ball value) {
        if (ballBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ball_ = value;
          onChanged();
        } else {
          ballBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public Builder setBall(
          pong.Api.Ball.Builder builderForValue) {
        if (ballBuilder_ == null) {
          ball_ = builderForValue.build();
          onChanged();
        } else {
          ballBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public Builder mergeBall(pong.Api.Ball value) {
        if (ballBuilder_ == null) {
          if (ball_ != null) {
            ball_ =
              pong.Api.Ball.newBuilder(ball_).mergeFrom(value).buildPartial();
          } else {
            ball_ = value;
          }
          onChanged();
        } else {
          ballBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public Builder clearBall() {
        if (ballBuilder_ == null) {
          ball_ = null;
          onChanged();
        } else {
          ball_ = null;
          ballBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public pong.Api.Ball.Builder getBallBuilder() {
        
        onChanged();
        return getBallFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      public pong.Api.BallOrBuilder getBallOrBuilder() {
        if (ballBuilder_ != null) {
          return ballBuilder_.getMessageOrBuilder();
        } else {
          return ball_ == null ?
              pong.Api.Ball.getDefaultInstance() : ball_;
        }
      }
      /**
       * <code>optional .pong.Ball ball = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pong.Api.Ball, pong.Api.Ball.Builder, pong.Api.BallOrBuilder> 
          getBallFieldBuilder() {
        if (ballBuilder_ == null) {
          ballBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pong.Api.Ball, pong.Api.Ball.Builder, pong.Api.BallOrBuilder>(
                  getBall(),
                  getParentForChildren(),
                  isClean());
          ball_ = null;
        }
        return ballBuilder_;
      }

      private boolean hit_ ;
      /**
       * <code>optional bool hit = 3;</code>
       */
      public boolean getHit() {
        return hit_;
      }
      /**
       * <code>optional bool hit = 3;</code>
       */
      public Builder setHit(boolean value) {
        
        hit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool hit = 3;</code>
       */
      public Builder clearHit() {
        
        hit_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pong.PongData)
    }

    // @@protoc_insertion_point(class_scope:pong.PongData)
    private static final pong.Api.PongData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pong.Api.PongData();
    }

    public static pong.Api.PongData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PongData>
        PARSER = new com.google.protobuf.AbstractParser<PongData>() {
      public PongData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PongData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PongData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PongData> getParserForType() {
      return PARSER;
    }

    public pong.Api.PongData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pong.Bat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code pong.Bat}
   */
  public  static final class Bat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pong.Bat)
      BatOrBuilder {
    // Use Bat.newBuilder() to construct.
    private Bat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bat() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Bat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pong.Api.internal_static_pong_Bat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pong.Api.internal_static_pong_Bat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pong.Api.Bat.class, pong.Api.Bat.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pong.Api.Bat)) {
        return super.equals(obj);
      }
      pong.Api.Bat other = (pong.Api.Bat) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pong.Api.Bat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.Bat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.Bat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.Bat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.Bat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.Bat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.Bat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pong.Api.Bat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.Bat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.Bat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pong.Api.Bat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pong.Bat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pong.Bat)
        pong.Api.BatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pong.Api.internal_static_pong_Bat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pong.Api.internal_static_pong_Bat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pong.Api.Bat.class, pong.Api.Bat.Builder.class);
      }

      // Construct using pong.Api.Bat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pong.Api.internal_static_pong_Bat_descriptor;
      }

      public pong.Api.Bat getDefaultInstanceForType() {
        return pong.Api.Bat.getDefaultInstance();
      }

      public pong.Api.Bat build() {
        pong.Api.Bat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pong.Api.Bat buildPartial() {
        pong.Api.Bat result = new pong.Api.Bat(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pong.Api.Bat) {
          return mergeFrom((pong.Api.Bat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pong.Api.Bat other) {
        if (other == pong.Api.Bat.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pong.Api.Bat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pong.Api.Bat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pong.Bat)
    }

    // @@protoc_insertion_point(class_scope:pong.Bat)
    private static final pong.Api.Bat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pong.Api.Bat();
    }

    public static pong.Api.Bat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bat>
        PARSER = new com.google.protobuf.AbstractParser<Bat>() {
      public Bat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bat> getParserForType() {
      return PARSER;
    }

    public pong.Api.Bat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pong.Ball)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code pong.Ball}
   */
  public  static final class Ball extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pong.Ball)
      BallOrBuilder {
    // Use Ball.newBuilder() to construct.
    private Ball(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ball() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Ball(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pong.Api.internal_static_pong_Ball_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pong.Api.internal_static_pong_Ball_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pong.Api.Ball.class, pong.Api.Ball.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pong.Api.Ball)) {
        return super.equals(obj);
      }
      pong.Api.Ball other = (pong.Api.Ball) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pong.Api.Ball parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.Ball parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.Ball parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pong.Api.Ball parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pong.Api.Ball parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.Ball parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.Ball parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pong.Api.Ball parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pong.Api.Ball parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pong.Api.Ball parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pong.Api.Ball prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pong.Ball}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pong.Ball)
        pong.Api.BallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pong.Api.internal_static_pong_Ball_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pong.Api.internal_static_pong_Ball_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pong.Api.Ball.class, pong.Api.Ball.Builder.class);
      }

      // Construct using pong.Api.Ball.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pong.Api.internal_static_pong_Ball_descriptor;
      }

      public pong.Api.Ball getDefaultInstanceForType() {
        return pong.Api.Ball.getDefaultInstance();
      }

      public pong.Api.Ball build() {
        pong.Api.Ball result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pong.Api.Ball buildPartial() {
        pong.Api.Ball result = new pong.Api.Ball(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pong.Api.Ball) {
          return mergeFrom((pong.Api.Ball)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pong.Api.Ball other) {
        if (other == pong.Api.Ball.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pong.Api.Ball parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pong.Api.Ball) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pong.Ball)
    }

    // @@protoc_insertion_point(class_scope:pong.Ball)
    private static final pong.Api.Ball DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pong.Api.Ball();
    }

    public static pong.Api.Ball getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ball>
        PARSER = new com.google.protobuf.AbstractParser<Ball>() {
      public Ball parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Ball(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ball> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ball> getParserForType() {
      return PARSER;
    }

    public pong.Api.Ball getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_PongData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_PongData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_Bat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_Bat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_Ball_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_Ball_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\004pong\"I\n\010PongData\022\026\n\003bat\030\001 \001" +
      "(\0132\t.pong.Bat\022\030\n\004ball\030\002 \001(\0132\n.pong.Ball\022" +
      "\013\n\003hit\030\003 \001(\010\"\033\n\003Bat\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(" +
      "\005\"\034\n\004Ball\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\0052y\n\013PongS" +
      "ervice\0224\n\014ClientStream\022\016.pong.PongData\032\016" +
      ".pong.PongData\"\000(\0010\001\0224\n\014ServerStream\022\016.p" +
      "ong.PongData\032\016.pong.PongData\"\000(\0010\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pong_PongData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pong_PongData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_PongData_descriptor,
        new java.lang.String[] { "Bat", "Ball", "Hit", });
    internal_static_pong_Bat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pong_Bat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_Bat_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_pong_Ball_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pong_Ball_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_Ball_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
