// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.hashicorp.pong;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_PongData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_PongData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_Bat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_Bat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pong_Ball_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pong_Ball_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\004pong\"I\n\010PongData\022\026\n\003bat\030\001 \001" +
      "(\0132\t.pong.Bat\022\030\n\004ball\030\002 \001(\0132\n.pong.Ball\022" +
      "\013\n\003hit\030\003 \001(\010\"\033\n\003Bat\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(" +
      "\005\"\034\n\004Ball\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\0052y\n\013PongS" +
      "ervice\0224\n\014ClientStream\022\016.pong.PongData\032\016" +
      ".pong.PongData\"\000(\0010\001\0224\n\014ServerStream\022\016.p" +
      "ong.PongData\032\016.pong.PongData\"\000(\0010\001B\026\n\022co" +
      "m.hashicorp.pongP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pong_PongData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pong_PongData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_PongData_descriptor,
        new java.lang.String[] { "Bat", "Ball", "Hit", });
    internal_static_pong_Bat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pong_Bat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_Bat_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_pong_Ball_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pong_Ball_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pong_Ball_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
