// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.hashicorp.pong;

public interface BallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pong.Ball)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>optional int32 y = 2;</code>
   */
  int getY();
}
