// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.hashicorp.pong;

public interface PongDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pong.PongData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .pong.Bat bat = 1;</code>
   */
  boolean hasBat();
  /**
   * <code>optional .pong.Bat bat = 1;</code>
   */
  com.hashicorp.pong.Bat getBat();
  /**
   * <code>optional .pong.Bat bat = 1;</code>
   */
  com.hashicorp.pong.BatOrBuilder getBatOrBuilder();

  /**
   * <code>optional .pong.Ball ball = 2;</code>
   */
  boolean hasBall();
  /**
   * <code>optional .pong.Ball ball = 2;</code>
   */
  com.hashicorp.pong.Ball getBall();
  /**
   * <code>optional .pong.Ball ball = 2;</code>
   */
  com.hashicorp.pong.BallOrBuilder getBallOrBuilder();

  /**
   * <code>optional bool hit = 3;</code>
   */
  boolean getHit();
}
